package preflight

import (
	"fmt"
	"os"
	"strings"

	"github.com/disentangle-network/launch/internal/exec"
)

type CredentialCheck struct {
	Name   string
	Status string // "ok", "missing", "invalid"
	Detail string
}

func CheckCredentials() []CredentialCheck {
	var results []CredentialCheck

	results = append(results, checkOCI())
	results = append(results, checkCloudflare())
	results = append(results, checkGitHub())
	results = append(results, checkAgeKey())

	return results
}

func checkOCI() CredentialCheck {
	result := CredentialCheck{Name: "OCI API Key"}

	// Check if ~/.oci/config exists
	home, err := os.UserHomeDir()
	if err != nil {
		result.Status = "missing"
		result.Detail = "cannot determine home directory"
		return result
	}
	ociConfig := home + "/.oci/config"
	if _, err := os.Stat(ociConfig); os.IsNotExist(err) {
		result.Status = "missing"
		result.Detail = "~/.oci/config not found"
		return result
	}

	// Validate with API call
	runner := exec.NewRunner()
	out, err := runner.RunSilent("oci", "iam", "region", "list", "--output", "json")
	if err != nil {
		result.Status = "invalid"
		result.Detail = fmt.Sprintf("OCI API call failed: %s", strings.TrimSpace(out.Stderr))
		return result
	}

	result.Status = "ok"
	result.Detail = "authenticated successfully"
	return result
}

func checkCloudflare() CredentialCheck {
	result := CredentialCheck{Name: "Cloudflare API Token"}

	token := os.Getenv("CLOUDFLARE_API_TOKEN")
	if token != "" {
		runner := exec.NewRunner()
		out, err := runner.RunSilent("curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
			"-H", "Authorization: Bearer "+token,
			"https://api.cloudflare.com/client/v4/user/tokens/verify")
		if err != nil {
			result.Status = "invalid"
			result.Detail = "token verification request failed"
			return result
		}

		if strings.TrimSpace(out.Stdout) == "200" {
			result.Status = "ok"
			result.Detail = "token valid"
		} else {
			result.Status = "invalid"
			result.Detail = fmt.Sprintf("token verification returned HTTP %s", strings.TrimSpace(out.Stdout))
		}
		return result
	}

	// Fallback: check if wrangler is authenticated
	if exec.CommandExists("wrangler") {
		runner := exec.NewRunner()
		out, err := runner.RunSilent("wrangler", "whoami")
		if err == nil && !strings.Contains(out.Stdout, "not authenticated") {
			result.Status = "ok"
			result.Detail = "authenticated via wrangler (set CLOUDFLARE_API_TOKEN for non-interactive use)"
			return result
		}
	}

	result.Status = "missing"
	result.Detail = "CLOUDFLARE_API_TOKEN not set"
	return result
}

func checkGitHub() CredentialCheck {
	result := CredentialCheck{Name: "GitHub CLI"}

	runner := exec.NewRunner()
	out, err := runner.RunSilent("gh", "auth", "status")
	if err != nil {
		result.Status = "invalid"
		result.Detail = fmt.Sprintf("gh auth failed: %s", strings.TrimSpace(out.Stderr))
		return result
	}

	result.Status = "ok"
	// Extract username from output
	output := out.Stdout + out.Stderr
	if idx := strings.Index(output, "Logged in to"); idx >= 0 {
		result.Detail = strings.TrimSpace(output[idx:])
		if nl := strings.IndexByte(result.Detail, '\n'); nl >= 0 {
			result.Detail = result.Detail[:nl]
		}
	} else {
		result.Detail = "authenticated"
	}
	return result
}

func checkAgeKey() CredentialCheck {
	result := CredentialCheck{Name: "SOPS Age Key"}

	// Check SOPS_AGE_KEY_FILE env var or default location
	keyFile := os.Getenv("SOPS_AGE_KEY_FILE")
	if keyFile == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			result.Status = "missing"
			result.Detail = "cannot determine home directory"
			return result
		}
		keyFile = home + "/.config/sops/age/keys.txt"
	}

	if _, err := os.Stat(keyFile); os.IsNotExist(err) {
		result.Status = "missing"
		result.Detail = fmt.Sprintf("age key file not found at %s (will be generated by 'launch infra')", keyFile)
		return result
	}

	result.Status = "ok"
	result.Detail = fmt.Sprintf("key file found at %s", keyFile)
	return result
}

func AllCredentialsOK(checks []CredentialCheck) bool {
	for _, c := range checks {
		if c.Status != "ok" && c.Status != "missing" {
			return false
		}
	}
	return true
}
